#!/usr/bin/env bash
#TODO: email me when successful or fails. Systemd?
# some helpers and error handling:
info() { printf "\n%s %s\n\n" "$(date --iso-8601=seconds)" "$*" >&2; }
trap 'echo ${red}$(date --iso-8601=seconds) Backup interrupted${reset} >&2; exit 2' INT TERM

info "Starting backup"

borg create \
	--remote-path=borg1 \
	--verbose \
	--stats \
	::{hostname}-{now:%Y-%m-%d} ~ \
	--exclude ~/Dropbox \
	--exclude ~/.dropbox \
	--exclude ~/.dropbox-dist \
	--exclude ~/.steam \
	--exclude ~/.cache \
	--exclude ~/.mozilla \
	--exclude-if-present '.git' \
	--exclude-caches

backup_exit=$?

info "Pruning repository"

borg prune \
	--remote-path=borg1 \
	--list \
	--prefix '{hostname}-' \
	--keep-daily 7 \
	--keep-weekly 4 \
	--keep-monthly 6

prune_exit=$?

# use highest exit code as global exit code
global_exit=$(( backup_exit > prune_exit ? backup_exit : prune_exit ))

if [ ${global_exit} -eq 0 ]; then
    info "Backup and Prune finished successfully"
elif [ ${global_exit} -eq 1 ]; then
    info "Backup and/or Prune finished with warnings"
else
    info "Backup and/or Prune finished with errors"
fi

exit ${global_exit}

