#!/bin/bash

alias b=bundle
alias be='bundle exec'
alias bjs="bundle exec jekyll serve"
alias bm='bundle exec rake db:migrate'
alias brownnoise='play -c 2 -n synth brownnoise'
alias c="cargo"
alias cb="cargo build"
alias cl="clear"
alias cr="cargo run"
alias ct="cargo test"
alias cw="cargo watch"
alias dbresetseed="bundle exec rake db:migrate:reset && bundle exec rake db:seed"
alias ef="exercism fetch"
alias es="exercism submit"
alias exc="~/code/programming-problems/exercism.io"
alias gu=guard
alias gw="gcc -Wconversion"
alias id_rsa="pass -c id_rsa"
alias ls='ls --color --group-directories-first -F'
alias n=nvim
alias news="newsbeuter"
alias pinknoise='play -c 2 -n synth pinknoise'
alias ra=rails
alias rc="rails console"
alias rs="rails server"
alias tl="tmux ls"
alias vg="vimgolf put"
alias whitenoise='play -c 2 -n synth whitenoise'
alias zc="nvim ~/.zshrc"
alias zr=". ~/.zshrc"
alias xstuff="xrandr --output DP2 --auto"
# TODO this should be a script that hooks into a keyboard being inserted
alias keyboard="xmodmap ~/.Xmodmap; xbindkeys; xcape"
alias ssh-bit="ssh-add -t 7200 ~/.ssh/bit-bucket"
alias bi="beet import"
alias update="pacaur -Syyu"
alias uninstall="pacaur -Rns"

# disk space usage
alias df='df -kh'
# file space usage
alias du='du -kh'
alias _='sudo'
alias get='curl --continue-at - --location --progress-bar --remote-name --remote-time'
alias z="zathura"
alias aon="source /opt/anaconda2/bin/activate root"
alias aoff="source /opt/anaconda2/bin/deactivate root"
source /home/nash/code/fastai/courses/setup/aws-alias.sh
alias aws-mount-t2="sshfs -C ubuntu@35.166.12.90: /home/nash/code/fastai/t2 -o IdentityFile=/home/nash/.ssh/aws-key.pem"
alias aws-mount-p2="sshfs -C ubuntu@35.167.166.118: /home/nash/code/fastai/p2 -o IdentityFile=/home/nash/.ssh/aws-key.pem"
alias pkg-info="pacaur -Si"
alias jnb="jupyter-notebook"
alias fbr="FBReader"
