#! /bin/sh

bspc config border_width        0
bspc config window_gap         20
bspc config focus_follows_pointer   true

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config initial_polarity second_child
bspc config ignore_ewmh_focus true

# Workspace *
bspc rule -a firefox floating=on
bspc rule -a feh floating=on
bspc rule -a file-roller floating=on
bspc rule -a dmenu border=on
bspc rule -a thunar floating=on

# Launches mpd
mpd &

# autom usb mount
devmon &

# Compton
compton --config ~/.config/compton/compton.conf &
#compton --backend glx --paint-on-overlay --vsync opengl-swc &
