#! /bin/sh

bspc config border_width            10
bspc config window_gap              20
bspc config focus_follows_pointer   true

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config top_padding         15
bspc config initial_polarity    second_child
bspc config ignore_ewmh_focus   true

# Workspace *
bspc rule -a connman-gtk floating=on
bspc rule -a dmenu border=on
bspc rule -a feh floating=on
bspc rule -a file-roller floating=on
bspc rule -a firefox floating=on
bspc rule -a nautilus floating=on
bspc rule -a pavucontrol floating=on
bspc rule -a thunar floating=on

# set wallpaper
$XDG_CONFIG_HOME/feh/fehbg &

# lemonbar startup
# TODO: move font stuff to the script itself. It doesn't belong here!
$XDG_CONFIG_HOME/panel/bar.sh | lemonbar -p -f "Input\ Mono\ Medium:size=8" -B#000&

# redshift
redshift -l 41.04:-73.71 &

# autom usb mount
devmon &

# Compton
compton --config $XDG_CONFIG_HOME/compton/compton.conf &

# screen locking with xautlock and slock
xautolock -time 10 -locker slock &
