#! /bin/sh

sxhkd &

compton &

polybar top &

# make java gui apps work
wmane LG3D

bspc monitor -d code web mail books music

bspc config border_width          2
bspc config window_gap            0

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focused_border_color  '#26a98b'
bspc config border_width          3
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a 'Zotero:Toplevel' state=floating follow=on
bspc rule -a anki state=floating follow=on
bspc rule -a 'libreoffice:libreoffice-writer' state=tiled
bspc rule -a Chromium desktop='^2'
bspc rule -a Firefox desktop='^2'
bspc rule -a calibre desktop='^4'
bspc rule -a  desktop='^2'
bspc rule -a 'Connman-gtk' state=floating
bspc rule -a 'Chromium:crx_ekhagklcjbdpajgpjgmbionohlpdbjgc' state=floating follow=on
bspc rule -a zathura state=tiled


