#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
#

# run startx at login
if [[ $(tty) == /dev/tty1 ]]; then
  exec startx
fi

# No arguments: `git status`
# With arguments: acts like `git`
g() {
  if [[ $# > 0 ]]; then
    hub $@
  else
    hub status --short --branch
  fi
}

al() {
  if [[ $# > 0 ]]; then
    if type $1 > /dev/null; then
      echo "Error: command" $1 "exists" 1>&2
      return 1
    else
      echo alias $1=\"$2\" >> ~/.aliases
    fi
  else
    nvim ~/.aliases
  fi
  source ~/.aliases
}

# auto attach tmux session when shell is opened
_not_inside_tmux() {
  [[ -z "$TMUX" ]]
}

ensure_tmux_is_running() {
  if _not_inside_tmux; then
    tat
  fi
}

ensure_tmux_is_running

# Complete g like git
compdef g=git

source /usr/share/chruby/chruby.sh
source /usr/share/chruby/auto.sh
chruby 2.3.0

# TODO: make a shell function za which will without arguments open the alias file
# or with arguments will make the first argument an alias for the second and reload the config

em() {
  emacs $1 &> /dev/null &
}

# aliases
if [ -f ~/.aliases ]; then
  source ~/.aliases
fi

# environment variable definitions
if [ -f ~/.aliases ]; then
  source ~/.env_var
fi

# syntax highlighting in z shell
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
