#!/bin/bash

alias aliases='nvim ~/.bash_aliases'
alias code='cd ~/code'
alias d='cd ~/.files'
alias ls='ls --color --group-directories-first'
alias g='git'
alias be='bundle exec'
# extends to git to make use with github easier
alias git='hub'
# use nvim for vimdiff
alias vimdiff='nvim -d'
