# script for git completion
if [ -f ~/git-completion.bash ]; then
  source ~/.git-completion.bash
fi
# aliases
if [ -f ~/.bash_aliases ]; then
  source ~/.bash_aliases
fi

# environment variables
if [ -f ~/.env_var ]; then
  source ~/.env_var
fi

# run startx at login
if [[ $(tty) == /dev/tty1 ]]; then
  exec startx
fi
# Run twolfson/sexy-bash-prompt
if [ -f ~/.bash_prompt ]; then
  source ~/.bash_prompt
fi

# auto attach tmux session when shell is opened
_not_inside_tmux() {
  [[ -z "$TMUX" ]]
}

ensure_tmux_is_running() {
  if _not_inside_tmux; then
    tat
  fi
}

ensure_tmux_is_running

source /usr/share/chruby/chruby.sh
source /usr/share/chruby/auto.sh
