# script for git completion
source ~/.git-completion.bash

# environment variables
export VISUAL='nvim'
PATH=$PATH:/home/nash/.gem/ruby/2.2.0/bin
export PATH

# aliases
# compile and run java source with junit
# pretty colors and directories first with ls
alias ls='ls --color --group-directories-first'
alias junitc='javac -cp .:/opt/junit-4.12/junit-4.12.jar'
alias junit='java -cp .:/opt/junit-4.12/junit-4.12.jar:/opt/junit-4.12/hamcrest-core-1.3.jar org.junit.runner.JUnitCore'
alias c++='g++ -std=c++14'
alias wifi='sudo bash ~/restart-wifi.sh'
# updates pacman's mirror list with the reflector tool
alias umirror='sudo reflector --sort rate --save /etc/pacman.d/mirrorlist -c "United States"'
# connman gui
alias cg='connman-gtk'
# tarsnap backup
alias tbackup='sudo /root/tarsnap-backup.sh'
