#!/bin/bash

alias aliases='nvim ~/.bash_aliases'
alias code='cd ~/code'
alias d='cd ~/.files'
alias cg='connman-gtk'
alias ls='ls --color --group-directories-first'
alias g='git'
alias be='bundle exec'
